"""
meta_labeler.py — Lopez de Prado meta-labeling secondary classifier.

Why this exists
---------------
The standard single-classifier approach trains one model to predict both
*side* (BUY/SELL) and *size* (how confident). That conflates two very
different problems. Lopez de Prado (Advances in Financial Machine
Learning, ch. 3) showed that a cleaner split gives substantially better
Sharpe and drawdown characteristics:

  1. A PRIMARY model picks the SIDE (direction) — high recall, may have
     many false positives.
  2. A SECONDARY (meta) model picks whether to ACT on the primary's
     call — high precision, gates and sizes.

In TrendMaster v14:

  * PRIMARY = the existing stack (ML brain + 3-of-3 agents + profit
    filters + risk manager). Already tuned for recall (too many
    signals => filter stack removes most).
  * META   = a new binary classifier: "given this primary's BUY/SELL
    and current features, will this trade PnL > 0?". Output is a
    probability we use BOTH as a gate (skip if p_win < threshold)
    and as a size scaler (multiply base lot by p_win).

Why this is the right fix for the CRYPTO model
----------------------------------------------
The CRYPTO per-team model's 99.2% WR is almost certainly label
leakage. Meta-labeling structurally avoids this: the meta-model only
ever sees a feature vector at DECISION time plus the primary's
direction. The label is computed from the FORWARD trade outcome
(which is generated by the primary's own trading decisions), so
"train on N rows, test on next N rows" gives an honest estimate.

Design
------
- Pure-Python + numpy + scikit-learn (sklearn is already in
  requirements — no new dep). LightGBM is OPTIONAL for upgrade.
- Returns a structured prediction with p_win, recommended scale,
  and a reason string.
- Honest null — if the meta-model isn't trained, returns scale=1.0
  (fall back to primary).
- Training takes the CPCV splitter from `tools/cpcv.py` so out-of-
  fold metrics are trustworthy.

Usage
-----
    from ai_trading_agents.meta_labeler import MetaLabeler
    mlb = MetaLabeler.load("ai_trading_agents/ml_models/meta_METALS.pkl")
    out = mlb.predict(features_dict, primary_direction="BUY")
    if out.act:
        adjusted_lots = base_lots * out.scale
"""
from __future__ import annotations

import logging
import math
import pickle
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

import numpy as np

logger = logging.getLogger("meta_labeler")


@dataclass
class MetaConfig:
    """Tuning knobs. Stored alongside the model so inference matches training."""
    p_win_threshold:   float = 0.55     # don't act unless meta ≥ this
    min_scale:         float = 0.5      # floor on size scale (p_win * 2)
    max_scale:         float = 1.5      # ceiling
    use_logistic_cal:  bool  = True     # Platt-style scaling on p_win
    feature_order:     List[str] = field(default_factory=list)


@dataclass
class MetaPrediction:
    p_win:     float
    act:       bool
    scale:     float        # multiplier for lot size
    reason:    str

    def as_dict(self) -> dict:
        return {
            "p_win":  round(self.p_win, 4),
            "act":    self.act,
            "scale":  round(self.scale, 4),
            "reason": self.reason,
        }


@dataclass
class MetaLabeler:
    """Wrap a sklearn binary classifier with side-aware gating + size scaling.

    The primary `direction` is fed as a binary feature (1=BUY, -1=SELL)
    alongside the regular features. That way a single meta-model covers
    both sides — no duplicate training. The meta-model's output is
    p(the trade will be a winner regardless of side).
    """
    model:     Optional[Any]         = None
    cfg:       MetaConfig            = field(default_factory=MetaConfig)
    trained:   bool                  = False
    metrics:   Dict[str, float]      = field(default_factory=dict)

    # ──────────────────────────────────────────────────────────────────
    # Inference
    # ──────────────────────────────────────────────────────────────────
    def predict(self,
                features: Dict[str, float],
                primary_direction: str) -> MetaPrediction:
        # Direction check FIRST — an invalid direction should be rejected
        # regardless of whether the meta-model is trained. (A null labeler
        # should still never claim to act on a NONE signal.)
        if primary_direction not in ("BUY", "SELL"):
            return MetaPrediction(
                p_win=0.0, act=False, scale=0.0,
                reason=f"unexpected primary direction: {primary_direction}",
            )
        if not self.trained or self.model is None:
            return MetaPrediction(
                p_win=0.5, act=True, scale=1.0,
                reason="meta-model not trained — primary passes through",
            )
        side_feat = 1.0 if primary_direction == "BUY" else -1.0
        x = self._row_from_dict(features, side_feat)
        try:
            # sklearn classifiers: predict_proba returns [[p0, p1]].
            p = float(self.model.predict_proba(x.reshape(1, -1))[0, 1])
        except Exception as e:
            return MetaPrediction(
                p_win=0.5, act=True, scale=1.0,
                reason=f"meta inference failed ({e!r}) — passthrough",
            )

        thr = float(self.cfg.p_win_threshold)
        act = p >= thr
        # Scale: map p in [thr, 1.0] onto [1.0, max_scale] linearly.
        if not act:
            scale = 0.0
        else:
            if p >= 1.0 or thr >= 1.0:
                scale = self.cfg.max_scale
            else:
                span = 1.0 - thr
                scale = 1.0 + (p - thr) / span * (self.cfg.max_scale - 1.0)
        scale = float(max(self.cfg.min_scale, min(self.cfg.max_scale, scale)) if act else 0.0)
        reason = (f"p_win={p:.3f} {'≥' if act else '<'} threshold={thr:.2f}"
                  f" → scale={scale:.2f}")
        return MetaPrediction(p_win=p, act=act, scale=scale, reason=reason)

    def _row_from_dict(self, features: Dict[str, float], side_feat: float) -> np.ndarray:
        order = list(self.cfg.feature_order)
        if not order:
            # Unknown feature order — use deterministic sort so the row
            # lines up with training if the model saved without it.
            order = sorted(features.keys())
        vals = [float(features.get(k, 0.0) or 0.0) for k in order]
        vals.append(float(side_feat))
        return np.asarray(vals, dtype=float)

    # ──────────────────────────────────────────────────────────────────
    # Training
    # ──────────────────────────────────────────────────────────────────
    @classmethod
    def train(cls,
              X: np.ndarray,
              y: np.ndarray,
              side: np.ndarray,
              *,
              feature_order: Sequence[str],
              cv_splitter: Optional[Any] = None,
              cfg: Optional[MetaConfig] = None,
              model_factory: Optional[Any] = None) -> "MetaLabeler":
        """Train a meta-model with optional CPCV splitter for honest OOS metrics.

        Parameters
        ----------
        X : (N, F) array of features
        y : (N,)  binary {0,1} — 1 if the trade the primary picked would
            have been a winner.
        side : (N,) array of {+1, -1} (BUY/SELL). Concatenated onto X
            column-wise before fit so a single meta-model handles both.
        cv_splitter : any sklearn-compatible CV iterator. If None, a
            simple 80/20 holdout is used (NOT recommended for live).
        model_factory : zero-arg callable returning a fresh sklearn
            classifier. Default: LogisticRegression — low variance,
            reasonable baseline. Swap for LightGBM once data allows.
        """
        from sklearn.linear_model import LogisticRegression
        from sklearn.metrics import (
            accuracy_score, precision_score, recall_score, f1_score,
            roc_auc_score,
        )

        cfg = cfg or MetaConfig(feature_order=list(feature_order))
        if not cfg.feature_order:
            cfg.feature_order = list(feature_order)
        model_factory = model_factory or (
            lambda: LogisticRegression(max_iter=500, class_weight="balanced")
        )

        X = np.asarray(X, dtype=float)
        y = np.asarray(y, dtype=int)
        side = np.asarray(side, dtype=float)
        # Append side as the last column.
        X_full = np.hstack([X, side.reshape(-1, 1)])

        if cv_splitter is None:
            n = len(X_full)
            split = int(n * 0.8)
            train_idx = np.arange(split)
            test_idx = np.arange(split, n)
            model = model_factory()
            model.fit(X_full[train_idx], y[train_idx])
            proba = model.predict_proba(X_full[test_idx])[:, 1]
            preds = (proba >= cfg.p_win_threshold).astype(int)
            metrics = _oof_metrics(y[test_idx], preds, proba)
        else:
            # Average metrics across CV folds; refit on full data for inference.
            oof_true: List[int] = []
            oof_pred: List[int] = []
            oof_prob: List[float] = []
            for tr, te in cv_splitter.split(X_full, y):
                m = model_factory()
                m.fit(X_full[tr], y[tr])
                p = m.predict_proba(X_full[te])[:, 1]
                oof_true.extend(y[te].tolist())
                oof_pred.extend((p >= cfg.p_win_threshold).astype(int).tolist())
                oof_prob.extend(p.tolist())
            metrics = _oof_metrics(
                np.asarray(oof_true), np.asarray(oof_pred), np.asarray(oof_prob),
            )
            model = model_factory()
            model.fit(X_full, y)

        return cls(model=model, cfg=cfg, trained=True, metrics=metrics)

    # ──────────────────────────────────────────────────────────────────
    # Persistence
    # ──────────────────────────────────────────────────────────────────
    def save(self, path: str) -> None:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "wb") as f:
            pickle.dump({
                "model":   self.model,
                "cfg":     self.cfg,
                "trained": self.trained,
                "metrics": self.metrics,
            }, f)

    @classmethod
    def load(cls, path: str) -> "MetaLabeler":
        p = Path(path)
        if not p.exists():
            return cls()
        try:
            with open(p, "rb") as f:
                blob = pickle.load(f)
            return cls(
                model=blob.get("model"),
                cfg=blob.get("cfg") or MetaConfig(),
                trained=bool(blob.get("trained")),
                metrics=dict(blob.get("metrics") or {}),
            )
        except Exception as e:
            logger.warning("meta-model load failed (%s) — returning null labeler", e)
            return cls()


def _oof_metrics(y_true, y_pred, y_prob) -> Dict[str, float]:
    """Out-of-fold classification metrics; handles degenerate singles."""
    from sklearn.metrics import (
        accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    )
    out: Dict[str, float] = {}
    try:
        out["accuracy"] = float(accuracy_score(y_true, y_pred))
    except Exception:
        out["accuracy"] = math.nan
    try:
        out["precision"] = float(precision_score(y_true, y_pred, zero_division=0))
    except Exception:
        out["precision"] = math.nan
    try:
        out["recall"] = float(recall_score(y_true, y_pred, zero_division=0))
    except Exception:
        out["recall"] = math.nan
    try:
        out["f1"] = float(f1_score(y_true, y_pred, zero_division=0))
    except Exception:
        out["f1"] = math.nan
    try:
        # Handles both full-label and degenerate cases.
        out["auc_roc"] = float(roc_auc_score(y_true, y_prob))
    except Exception:
        out["auc_roc"] = math.nan
    return out


__all__ = ["MetaConfig", "MetaPrediction", "MetaLabeler"]
