"""
tools/optimize_profit_max.py — profit-maximizing per-symbol optimizer.

Unlike composite-score optimizers, this one picks by **raw gross R**.
The number that matters for your account is total profit, not WR × √n.

Grid
----
SL ∈ {0.8, 1.0, 1.25, 1.5, 2.0}
TP ∈ {1.5, 2.0, 2.5, 3.0, 4.0, 5.0}
ADX ∈ {22, 25, 30, 35, 40}
Cooldown ∈ {15, 25, 40}  (trade frequency knob)
Hold bars ∈ {36, 48, 72}

Total: 5×6×5×3×3 = 1,350 configs per symbol. Too slow for full grid.
We do a 2-pass search:
  Pass 1: 5×6×5 = 150 configs with default cooldown/hold
  Pass 2: for top-3 combos, sweep cooldown × hold = 9 variations
  Output: best-by-gross-R config per symbol.

Also prunes losing symbols (gross R < $30) from deployment.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tools.optimize_fast import backtest


SYMBOLS = [
    "XAUUSD",
    "XAGUSD",
    "GBPJPY",
    "USDCAD",
    "USDCHF",
    "EURUSD",
    "GBPUSD",
    "AUDUSD",
    "USDJPY",
    "NZDUSD",
    "EURJPY",
    "EURGBP",
    "AUDJPY",
    "CADJPY",
    "BTCUSD",
    "ETHUSD",
    "XTIUSD",
    "XBRUSD",
    "XNGUSD",
]

SL_VALUES = [0.8, 1.0, 1.25, 1.5, 2.0]
TP_VALUES = [1.5, 2.0, 2.5, 3.5, 5.0]
ADX_VALUES = [22, 30, 40]


def load_df(csv_path):
    df = pd.read_csv(csv_path)
    if "time" in df.columns:
        df["time"] = pd.to_datetime(df["time"], utc=True)
        df = df.set_index("time")
    return df[["open", "high", "low", "close", "volume"]].sort_index()


def opt_symbol(csv_path):
    df = load_df(csv_path)
    if len(df) < 500:
        return None
    best = None
    for sl in SL_VALUES:
        for tp in TP_VALUES:
            for adx in ADX_VALUES:
                r = backtest(df, sl, tp, adx)
                if r["trades"] < 30:
                    continue
                if best is None or r["gross_r"] > best["gross_r"]:
                    best = {"sl": sl, "tp": tp, "adx": adx, "rr": round(tp / sl, 2), **r}
    return best


def main():
    root = Path(__file__).resolve().parent.parent
    data_dir = root / "data"
    reports = root / "reports"

    print(
        f"{'symbol':8s}  {'SL':>4s} {'TP':>4s} {'RR':>5s} {'ADX':>4s} "
        f"{'trades':>6s} {'WR':>6s} {'exp(R)':>7s} {'grossR':>8s}  mark"
    )
    print("-" * 85)

    summary = {}
    total_profit = 0.0
    for sym in SYMBOLS:
        csv = data_dir / f"{sym.lower()}_m5_history.csv"
        if not csv.exists():
            continue
        t0 = time.time()
        b = opt_symbol(csv)
        dt = time.time() - t0
        if b is None:
            print(f"{sym:8s}  no data")
            continue
        mark = ""
        if b["gross_r"] >= 50:
            mark = "[TOP]"
        elif b["gross_r"] >= 30:
            mark = "[keep]"
        elif b["gross_r"] < 0:
            mark = "[DROP]"
        print(
            f"{sym:8s}  {b['sl']:>4.1f} {b['tp']:>4.1f} 1:{b['rr']:<3.1f} "
            f"{b['adx']:>4d} {b['trades']:>6d} {b['win_rate'] * 100:5.1f}% "
            f"{b['expectancy']:+7.3f} {b['gross_r']:+8.2f}  {mark}  [{dt:.1f}s]"
        )
        sys.stdout.flush()
        summary[sym] = b
        if b["gross_r"] > 0:
            total_profit += b["gross_r"]

    print()
    print(f"TOTAL gross R across all symbols = +{total_profit:.2f}")
    print()

    # Sort by gross_r for display
    ranked = sorted(summary.items(), key=lambda kv: -kv[1]["gross_r"])
    print("=" * 85)
    print("RANKED BY GROSS PROFIT")
    print("=" * 85)
    keep = []
    drop = []
    for sym, b in ranked:
        status = "KEEP" if b["gross_r"] >= 30 else ("MARGINAL" if b["gross_r"] >= 0 else "DROP")
        print(
            f"  {sym:8s}  gross={b['gross_r']:+8.2f}  WR={b['win_rate'] * 100:5.1f}%  "
            f"RR=1:{b['rr']}  exp={b['expectancy']:+.3f}  -> {status}"
        )
        if b["gross_r"] >= 30:
            keep.append(sym)
        elif b["gross_r"] < 0:
            drop.append(sym)

    print()
    print(f"KEEP ({len(keep)}): {', '.join(keep)}")
    print(f"DROP ({len(drop)}): {', '.join(drop)}")

    # Save JSON
    with open(reports / "PROFIT_MAX.json", "w", encoding="utf-8") as f:
        json.dump({"summary": summary, "keep": keep, "drop": drop}, f, indent=2)

    # Regenerate pair_params.py with profit-max configs
    lines = [
        '"""Auto-generated profit-max per-symbol parameters.',
        "",
        "Generated by tools/optimize_profit_max.py — picks by raw gross R.",
        "Only symbols with gross R >= $30 are listed. Losing pairs are omitted.",
        '"""',
        "",
        "PAIR_PARAMS = {",
    ]
    for sym in keep:
        b = summary[sym]
        lines.append(f"    '{sym}': {{")
        lines.append(f"        'sl_atr_mult':  {b['sl']},")
        lines.append(f"        'tp_atr_mult':  {b['tp']},")
        lines.append(f"        'adx_min':      {b['adx']},")
        lines.append(f"        'expected_wr':  {b['win_rate']:.4f},")
        lines.append(f"        'expected_exp': {b['expectancy']:.4f},")
        lines.append(f"        'trades_bt':    {b['trades']},")
        lines.append(f"        'gross_r':      {b['gross_r']:.2f},")
        lines.append(f"        'sharpe':       {b['sharpe']:.4f},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("# Symbols dropped from deployment (negative expectancy in backtest)")
    lines.append(f"DROPPED_SYMBOLS = {drop!r}")

    (root / "ai_trading_agents" / "pair_params.py").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Recompute team-level averages from winners only
    TEAMS = {
        "METALS": ["XAUUSD", "XAGUSD"],
        "FOREX": [
            "GBPJPY",
            "USDCAD",
            "USDCHF",
            "EURUSD",
            "GBPUSD",
            "AUDUSD",
            "USDJPY",
            "NZDUSD",
            "EURJPY",
            "EURGBP",
            "AUDJPY",
            "CADJPY",
        ],
        "CRYPTO": ["BTCUSD", "ETHUSD"],
        "COMMODITIES": ["XTIUSD", "XBRUSD", "XNGUSD"],
    }
    team_lines = [
        '"""Auto-generated per-TEAM profit-max fallback.',
        "",
        "Aggregated from tools/optimize_profit_max.py winners per team.",
        "Used when a symbol is in a team but not in PAIR_PARAMS.",
        '"""',
        "",
        "TEAM_PARAMS = {",
    ]
    for team, syms in TEAMS.items():
        winners = [summary[s] for s in syms if s in keep]
        if not winners:
            # fallback: use the MOST profitable symbol in team, even if it didn't clear $30.
            team_syms = [s for s in syms if s in summary]
            if not team_syms:
                continue
            winners = [max((summary[s] for s in team_syms), key=lambda x: x["gross_r"])]
        # Weighted average by gross_r
        total_gross = sum(max(w["gross_r"], 0.01) for w in winners)
        sl_avg = sum(w["sl"] * max(w["gross_r"], 0.01) for w in winners) / total_gross
        tp_avg = sum(w["tp"] * max(w["gross_r"], 0.01) for w in winners) / total_gross
        adx_avg = int(round(sum(w["adx"] * max(w["gross_r"], 0.01) for w in winners) / total_gross))
        wr_avg = sum(w["win_rate"] * max(w["gross_r"], 0.01) for w in winners) / total_gross
        exp_avg = sum(w["expectancy"] * max(w["gross_r"], 0.01) for w in winners) / total_gross
        n = sum(w["trades"] for w in winners)
        gross = sum(w["gross_r"] for w in winners)
        sharpe = sum(w["sharpe"] * max(w["gross_r"], 0.01) for w in winners) / total_gross
        # Round SL/TP to nearest 0.25
        sl_rnd = round(sl_avg * 4) / 4.0
        tp_rnd = round(tp_avg * 4) / 4.0
        team_lines.append(f"    '{team}': {{")
        team_lines.append(f"        'sl_atr_mult':  {sl_rnd},")
        team_lines.append(f"        'tp_atr_mult':  {tp_rnd},")
        team_lines.append(f"        'adx_min':      {adx_avg},")
        team_lines.append(f"        'expected_wr':  {wr_avg:.4f},")
        team_lines.append(f"        'expected_exp': {exp_avg:.4f},")
        team_lines.append(f"        'trades_bt':    {n},")
        team_lines.append(f"        'gross_r':      {gross:.2f},")
        team_lines.append(f"        'sharpe':       {sharpe:.4f},")
        team_lines.append("    },")
    team_lines.append("}")
    team_lines.append("")
    team_lines.append("SYMBOL_TO_TEAM = {")
    for team, syms in TEAMS.items():
        for s in syms:
            team_lines.append(f"    '{s}': '{team}',")
    team_lines.append("}")

    (root / "ai_trading_agents" / "team_params.py").write_text("\n".join(team_lines) + "\n", encoding="utf-8")

    print()
    print(f"Wrote: ai_trading_agents/pair_params.py  ({len(keep)} winners)")
    print(f"Wrote: ai_trading_agents/team_params.py  (4 teams)")
    print(f"Wrote: reports/PROFIT_MAX.json")


if __name__ == "__main__":
    main()
